trigger:
  branches:
    include:
      - "master"
      - "develop"

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    displayName: Checkout repository

  - script: |
      git checkout $(Build.SourceBranchName)
      git push https://$(pat2)@github.com/Sciance-Inc/core.dashboards_store
