name: Run the Nightly Build

on:
  workflow_dispatch:
    branches:
      - master
  push:
    branches:
      - master
  schedule:
    - cron: "*/5 * * * *"

env:
  REGISTRY: ghcr.io
  REPOSITORY_NAME: ${{ github.repository }}

jobs:
  build_nightly:
    runs-on: [self-hosted, maas]
    strategy:
      matrix:
        configs:
          - pattern: .*rc+.*$
            tag: nightly-rc
            target: rc
          - pattern: .*dev+.*$
            tag: nightly-dev
            target: dev

    steps:
      # Get the latest release matching the matrix pattern
      - name: Get the latest release
        uses: joutvhu/get-release@v1
        id: get_release
        with:
          debug: true
          latest: true
          pattern: ${{ matrix.configs.pattern }}
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.CICD_PAT_TOKEN }}

      # Clone the repo
      - name: Checkout the release
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.get_release.outputs.tag_name }}
          token: ${{ secrets.CICD_PAT_TOKEN }}

      # Prepare build(x) by adding the SSH key to download the core relase
      - name: Adding the SSH key to the agent
        uses: MrSquaare/ssh-setup-action@v2
        with:
          host: github.com
          private-key: ${{ secrets.SSH_PRIVATE_KEY_GH_ACCESS }}

      - name: Configure the Builder
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ matrix.configs.tag }}
          context: .
          file: nightly/docker/Dockerfile
          pull: true
          build-args: |
            CORE_VERSION=${{ steps.get_release.outputs.tag_name }}
            TARGET=${{ matrix.configs.target }}
          ssh: |
            default=${{ env.SSH_AUTH_SOCK }}
